package org.invite.com.enums;

public enum RequestTypes {
    CREATE_STRUCTURE, CREATE_USER, AUTHENTICATE, CREATE_FACILITY, CREATE_SECURITY_FIRM,
    CREATE_FIRM, CREATE_EMPLOYEE, CREATE_SECURITY_GUARD, GRANT_INVITE_ACCESS, CREATE_RECEPTION,
    CREATE_INVITATION, ADD_SHIFT, SIGN_IN, SIGN_OUT, APPROVE_INVITATION, REJECT_INVITATION, APPROVE_ENTRY,
    UPDATE_TIME_IN, UPDATE_TIME_OUT, UPDATE_GATE_TIME_OUT, GET_ALL_STRUCTURES, DEACTIVATE_STRUCTURE,
    GET_FACILITY_CATEGORIES, GET_FIRMS_IN_A_STRUCTURE, DEACTIVATE_FIRM, DEACTIVATE_EMPLOYEE,
    GET_FIRM_EMPLOYEES, GET_INVITE_EMPLOYEES, GET_FIRM_VISITORS, SEARCH_BY_CODE, GET_APPROVED_INVITATIONS
}
