package org.invite.com.enums;

public enum ResultIds {
    REQUEST_FAILED, REQUEST_SUCCESSFUL, USER_CREATED, USER_NOT_CREATED, AUTHENTICATION_SUCCESSFUL,
    AUTHENTICATION_FAILED, VALIDATION_FAILED, FIRM_CREATED, EMPLOYEE_CREATED, ACCESS_GRANTED, ACCESS_DENIED,
    INVITATION_CREATED, SHIFT_ADDED, SIGNED_IN, SIGNED_OUT, APPROVE_SUCCESSFUL, DENY_SUCCESSFUL
}
